apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis
      containers:
      - name: redis
        image: redis:7-alpine
        resources:
          limits:
            cpu: 250m
            memory: 256M
        volumeMounts:
        - mountPath: "/data"
          name: redis
        ports:
        - containerPort: 6379